services:
  strapi:
    container_name: strapi
    build:
      context: .
    command: npm run develop
    env_file: .env
    environment:
      NODE_ENV: development
      DATABASE_CLIENT: mysql
      DATABASE_HOST: strapiDB
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      JWT_SECRET: dev_jwt_secret
      ADMIN_JWT_SECRET: dev_admin_jwt_secret
      APP_KEYS: dev_key1,dev_key2
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    depends_on:
      - strapiDB

  strapiDB:
    image: mysql:8.0
    container_name: strapiDB
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_ROOT_PASSWORD: strapi
    volumes:
      - strapi-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  strapi-data:
